config/routes.rb
Rails.application.routes.draw do
  # 實做新的 controller 去處理 callback
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
      get :feeds

      get :ranking
    end

    member do
      get :dashboard
      
      post :favorite
      post :unfavorite
      
      post :like
      post :unlike
    end
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :friend_list
    end
  end
  
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]  do
    member do
      post :confirm
      delete :reject
    end
  end

  resources :categories, only: :show
  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories 
    root "restaurants#index"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.from_omniauth(auth)
    #Case 1: Find existing user by facebook uid
    # User不是第一次用FB登入：可以用fb_uid找到現存User
    user = User.find_by_fb_uid(auth.uid)
    if user
      user.fb_token = auth.credentials.token
      user.save!
      return user
    end

    #Case 2: Find existing user by email
    # User是第一次用FB登入，但是也是用同一組信箱帳號註冊過，就可以拿出FB回傳的email，從資料庫搜尋現存的User
    existing_user = User.find_by_email(auth.info.email)
    if existing_user
      existing_user.fb_uid = auth.uid
      existing_user.fb_token = auth.credentials.token
      existing_user.save!
      return existing_user
    end


    #Case 3: Create new password
    # User沒有註冊過，且是第一次用FB登入，故需創建一個全新的User紀錄
    user = Use.new
    user.fb_uid = auth.uid
    user.fb_token = auth.credentials.token
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.save!
    return user
  end

  validates_presence_of :name
  mount_uploader :avatar, AvatarUploader

  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  # 「使用者收藏很多餐廳」的多對多關聯
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  # 「使用者追蹤很多使用者」
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  # 「使用者的追蹤者」
  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  #「使用者新增很多朋友」
  has_many :friendships, -> {where status: true}, dependent: :destroy
  has_many :friends, through: :friendships

  #「使用者的朋友邀請」
  has_many :inverse_friendships, -> {where status: true}, class_name: "Friendship", foreign_key:"friend_id"
  has_many :inviters, through: :inverse_friendships, source: :user

  has_many :unconfirm_friendships, -> {where status: false}, class_name: "Friendship", dependent: :destroy
  has_many :unconfirm_friends, through: :unconfirm_friendships, source: :friend
  has_many :request_friendships, -> {where status: false}, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy
  has_many :request_friends, through: :request_friendships, source: :user

  def friend_receiver?(user)
    self.friends.include?(user) || self.inviters.include?(user)
  end

  def unconfirm_friend?(user)
    self.unconfirm_friends.include?(user)
  end

  def all_friends
    friends = self.friends + self.inviters
    return friends.uniq
  end

  def following?(user)
    self.followings.include?(user)
  end
  
  def admin?
    self.role == "admin"
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    # You need to implement the method(from_omniauth) below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    
    if @user.persisted?
      # 如果User存在

      #this will throw if @user is not activated
      sign_in_and_redirect @user, event: :authentication  

      # 出現Flash提示訊息
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?

    else
      # 如果User不存在

      # 就把FB回傳的資料丟進Devise的註冊方法，在本地端建立一個新的User
      session["devise.facebook_data"] = request.env["omniauth.auth"]

      redirect_to new_user_registration_url
      
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :friend_list]

  def index
    @users = User.all
  end

  def show
    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings
    @followers = @user.followers
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def friend_list
    @friends = @user.all_friends 
    @unconfirm_friends = @user.unconfirm_friends
    @request_friends = @user.request_friends
  end


private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h3>修改檔案</h3>

      <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :intro, '自我介紹' %>
        <%= f.text_area :intro, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :avatar, '大頭照上傳' %>
        <%= image_tag @user.avatar if @user.avatar? %>
        <%= f.file_field :avatar %>
      </div>
      <div class="form-group">
        <%= f.submit "檔案更新" , class: "btn btn-primary"  %>
        <%= link_to "取消" , user_path(@user), class: "btn btn-default" %>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/friend_list.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="page-header">
        <h1 class="text-center">我的好友</h1>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @user.all_friends.count %> Friends</h3>
        </div>

          <ul class="list-group">
            <% @friends.each do |friend| %>
            <li class="list-group-item">
              <%= link_to user_path(friend) do %>
              <%= image_tag(friend.avatar, height: 50, width: 50, class: "img-circle") if friend.avatar?%>
              <%= image_tag "http://via.placeholder.com/50x50", class:"img-circle" unless friend.avatar? %>
              <strong><%= friend.name %></strong>
              <% end %>
              <div class="pull-right">
              <%= render partial: "shared/friend", locals: { user: friend }%>
              </div>
            </li>
            <% end %>
          </ul>

      </div>

    </div>
    <% if current_user == @user %>  
      <div class="col-xs-6 col-xs-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @user.unconfirm_friends.count %> 個等待接受好友</h3>
        </div>

          <ul class="list-group">
            <% @unconfirm_friends.each do |friend| %>
            <li class="list-group-item">
              <%= link_to user_path(friend) do %>
              <%= image_tag(friend.avatar, height: 50, width: 50, class: "img-circle") if friend.avatar?%>
              <%= image_tag "http://via.placeholder.com/50x50", class:"img-circle" unless friend.avatar? %>
              <strong><%= friend.name if friend.name? %>
              <%= friend.email.split("@").first unless friend.name? %></strong>
              <% end %>
              <div class="pull-right">
              <%= render partial: "shared/friend", locals: { user: friend }%>
              </div>
            </li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="col-xs-6 col-xs-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @user.request_friends.count %> 個好友邀請</h3>
        </div>

          <ul class="list-group">
            <% @request_friends.each do |friend| %>
            <li class="list-group-item">
              <%= link_to user_path(friend) do %>
              <%= image_tag(friend.avatar, height: 50, width: 50, class: "img-circle") if friend.avatar?%>
              <%= image_tag "http://via.placeholder.com/50x50", class:"img-circle" unless friend.avatar? %>
              <strong><%= friend.name %></strong>
              <% end %>
              <div class="pull-right">
              <%= link_to "接受好友邀請", confirm_friendship_path(@user, friend), class: "btn btn-primary", method: :post %>
              <%= link_to "拒絕好友邀請", reject_friendship_path(@user, friend), class: "btn btn-danger", method: :delete %>
              </div>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <ul class="nav nav-tabs">
      <li role="presentation">
        <%= link_to "首頁", root_path %>
      </li>
      <li role="presentation">
        <%= link_to "最新動態", feeds_restaurants_path %>
      </li>
      <li role="presentation">
        <%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %>
      </li>
      <li role="presentation" class="active">
        <%= link_to '美食達人', users_path %>
      </li>
    </ul>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h1 class="text-center">美食達人</h1>
      </div>
    </div>

      <% @users.each do |user| %>
        <div class="col-md-3 col-sm-4 col-xs-6 text-center user-item">
          <%= link_to user_path(user) do %>
            <%= image_tag(user.avatar, class: "img-rounded") if user.avatar? %>
            <%= image_tag "http://via.placeholder.com/128x128", class: "img-rounded" unless user.avatar? %>
            <h4>
              <%= user.name if user.name? %>
              <%= user.email.split("@").first unless user.name? %>
            </h4>
          <% end %>
            <%= render partial: "shared/follow", locals: {user: user} %>
            <%= render partial: "shared/friend", locals: {user: user} %>
        </div>
      <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="page-header">

        <div class="col-md-3 col-sm-4">

          <div class="text-center">
            <%= image_tag @user.avatar ,class:"img-responsive img-rounded" if @user.avatar?%>
             <%= image_tag "http://via.placeholder.com/350x350", class: "img-responsive img-rounded"  unless @user.avatar?%>
          </div>
        </div>

        <div class="col-md-9 col-sm-8">
          <% if @user.email == current_user.email %>
            <%= link_to '<i class="glyphicon glyphicon-pencil" aria-hidden="true" style="color:gray"></i> 修改'.html_safe, edit_user_path(@user), class: "navbar-right btn btn-default mark" %>
          <% end %>
          <h2>
            <%= @user.name if @user.name? %>
            <%= @user.email.split("@").first unless @user.name? %>
          </h2>
          <p><strong><%= @user.email %></strong></p>
          <ul class="list-unstyled list-inline">
            <li><strong><%= @commented_restaurants.count %> 已評論餐廳 ｜</strong></li>
            <li><strong><%= @favorited_restaurants.count %> 已收藏餐廳 ｜</strong></li>
            <li><strong><%= @followings.count %> Followings ｜</strong></li>
            <li><strong><%= @followers.count %> Followers ｜</strong></li>
            <li><strong><%= link_to 'Friend List', friend_list_user_path(@user), class: "btn btn-link " %> ｜</strong></li>
            <li><%= render partial: "shared/friend", locals: {user: @user} %></li>
          </ul>
          
          <div><%= simple_format @user.intro %></div>
          
        </div>
        <div class="clearfix"></div>

      </div>

      <br>

      <div class="col-md-4">
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title"><strong><%= @followings.count %></strong> Followings</h3>
          </div>

          <ul class="list-group">
            <% @followings.each do |following| %>
            <li class="list-group-item">
              <%= link_to user_path(following) do %>
              <%= image_tag(following.avatar, height: 30, width: 30, class: "img-circle") if following.avatar?%>
              <%= image_tag "http://via.placeholder.com/30x30", class:"img-circle" unless following.avatar? %>
              <strong><%= following.name if following.name? %>
              <%= following.email.split("@").first unless following.name? %></strong>
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>

        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class = "panel-title"><strong><%= @followers.count %></strong> Followers</h3>
          </div>
          <ul class="list-group">
            <% @followers.each do |follower| %>
            <li class="list-group-item">
              <%= link_to user_path(follower) do %>
              <%= image_tag(follower.avatar, height:30, width:30, class: "img-circle") if follower.avatar? %>
              <%= image_tag "http://via.placeholder.com/30x30", class:"img-circle" unless follower.avatar? %>
              <%= follower.name %>
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="col-md-8">
        <div class ="panel panel-warning">
          <div class ="panel-heading">
             <h3 class="panel-title"><%= @commented_restaurants.count %> 間已評論餐廳</h3>
          </div>
          <div class="panel-body">
            <% @commented_restaurants.each do |restaurant| %>
              <div class="line-disappear my-restaurant">
                <%= link_to restaurant_path(restaurant) do %>
                  <div class="my-restaurant">
                    <div>
                      <%= image_tag restaurant.image, class:"img-responsive img-rounded" if restaurant.image? %>
                      <%= image_tag "http://via.placeholder.com/120x80", class:"img-responsive img-rounded" unless restaurant.image? %>
                    </div>
                    <h5><%= restaurant.name %></h5>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title"><%= @favorited_restaurants.count %> 間已收藏餐廳</h3>
          </div>
          <div class="panel-body">
            <% @favorited_restaurants.each do |restaurant| %>
              <div class="line-disappear my-restaurant">
                <%= link_to restaurant_path(restaurant) do %>
                  <div class="my-restaurant">
                    <div>
                      <%= image_tag restaurant.image, class:"img-responsive img-rounded" if restaurant.image? %>
                      <%= image_tag "http://via.placeholder.com/120x80", class:"img-responsive img-rounded" unless restaurant.image? %>
                    </div>
                    <h5><%= restaurant.name %></h5>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>