config/routes.rb
Rails.application.routes.draw do
  # 實做新的 controller 去處理 callback
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
      get :feeds

      get :ranking
    end

    member do
      get :dashboard
      
      post :favorite
      post :unfavorite
      
      post :like
      post :unlike
    end
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :friend_list
    end
  end
  
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]  do
    member do
      post :confirm
      delete :reject
    end
  end

  resources :categories, only: :show
  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories 
    root "restaurants#index"
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates_presence_of :name

    mount_uploader :image, PhotoUploader
    belongs_to :category, optional: true

    has_many :comments, dependent: :destroy

    # 「餐廳被很多使用者收藏」的多對多關聯
    has_many :favorites, dependent: :destroy
    has_many :favorited_users, through: :favorites, source: :user

    def is_favorited?(user)
      self.favorited_users.include?(user)
    end
    
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    def is_liked?(user)
      self.liked_users.include?(user)   
    end


end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

def index
  @restaurants = Restaurant.page(params[:page]).per(9)
end

   def new
      @restaurant = Restaurant.new
   end

  def create
      @restaurant = Restaurant.new(restaurant_params)
      if @restaurant.save
        flash[:notice] = "Successfully created"
        redirect_to admin_restaurants_path
      else
        flash.now[:alert] = "Failed to create"
        render :new
      end
    end

    def show
    end

    def edit
    end

    def update
      if @restaurant.update(restaurant_params)
        redirect_to admin_restaurants_path(@restaurant)
        flash[:notice] = "Successfully updated"
      else
        render :edit
        flash[:alert] = "Failed to update"
      end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "Successfully deleted"
  end
 


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
    
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
     @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])  
  end

  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    @restaurant.likes.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unlike
    @restaurant = Restaurant.find(params[:id])
    likes = Like.where(restaurant: @restaurant, user: current_user)
    likes.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def ranking
    @restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end
    
  end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<div class="container">
   <div class="row">
 
     <% if @restaurant.errors.any? %>
       <h4>We have some errors here !</h4>
       <ul>
         <% @restaurant.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
       <hr>
    <% end %>


      <%= form_for [:admin, @restaurant] do |f| %>
 
      <div class="form-group">
        <%= f.label :category %>
        <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: true}, {class: "form-control"} %>
      </div>

       <div class="form-group">
         <%= f.label :name, "Name" %>
         <%= f.text_field :name, class: "form-control" %>
       </div>
  

       <div class="form-group">
         <%= f.label :tel, "Tel" %>
         <%= f.text_field :tel, class: "form-control" %>
       </div>

      <div class="form-group">
        <%= f.label :address, "Address" %>
        <%= f.text_field :address, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :opening_hours, "Opening Hours" %>
        <%= f.text_field :opening_hours, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description, "Description" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :image, "Photo" %>
        <%= image_tag @restaurant.image, width: '300px' if @restaurant.image? %>
        <%= f.file_field :image %>
      </div>

      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>

  </div>
</div>

app/views/admin/restaurants/edit.html.erb
<%= render partial: "form" %>

app/views/admin/restaurants/index.html.erb
<div class="container">
   <h1 class="text-center">餐廳後台</h1>
   <div>
    <%= link_to 'Restaurant', admin_restaurants_path %> |
    <%= link_to 'Categories', admin_categories_path %>
  </div>

   <div class="row">
     <div class="col-md-12">
 
       <div>
         <%= link_to '<i class="glyphicon glyphicon-plus" aria-hidden="true"></i> New Restaurant'.html_safe, new_admin_restaurant_path, class: "btn btn-success center-block" %>
       </div>
       <br>
    </div>
  </div>

      <section>
        <div class="row">
         <% @restaurants.each do |restaurant| %>
          <div class="col-xs-12 col-sm-6 col-md-4 ">
            <div class="photo">
              <%= link_to admin_restaurant_path(restaurant) do %>
                <div>
                  <%= image_tag restaurant.image, class: ' img-rounded' , width:300 ,height:200 if restaurant.image?%>
                  <%= image_tag "http://via.placeholder.com/300x200", class: "img-responsive center-block img-rounded"  unless restaurant.image?%> 
                </div>
                <h3 style="color:slategray"  ><%= restaurant.name %></h3> 
                <p><%= truncate restaurant.description , length:140 %></p>
              <% end %>
              <div>
                <span class="mark label label-success"><%= restaurant.category.name %></span>
                <%= link_to '<i class="glyphicon glyphicon-pencil" aria-hidden="true" style="color:gray"></i> 編輯'.html_safe, edit_admin_restaurant_path(restaurant), class: 'btn btn-default' %>
                <%= link_to '<i class="glyphicon glyphicon-trash" aria-hidden="true" style="color:gray"></i> 刪除'.html_safe, admin_restaurant_path(restaurant), method: :delete, data: {confirm: "你確定要刪除嗎？"}, class: 'btn btn-default' %>
              </div>
            </div>
          </div>
         <% end %>
        </div>
      </section>

       <div class="text-center">
        <%= paginate @restaurants %>
      </div>
   </div>
 </div>

app/views/admin/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <h2>Error message!</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [:admin, @restaurant] do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %>

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>

  <%= f.label :opening_hours, "Opening Hours" %>
  <%= f.text_field :opening_hours %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/admin/restaurants/show.html.erb
<div class="container">
   <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
      <h4><span class="label label-success"><%= @restaurant.category.name %></span></h4>
    </div>

    <div class="col-md-4">
       <%= image_tag @restaurant.image, class: "img-responsive center-block" if @restaurant.image?%>
      <%= image_tag "http://via.placeholder.com/360x240", class: "img-responsive center-block img-rounded"  unless @restaurant.image?%> 
       <br>
       <div class="well">
         <dl class="dl-horizontal">
           <dt>Opening Hour:</dt> <dd> <%= @restaurant.opening_hours %></dd>
           <dt>Tel:</dt> <dd><%= @restaurant.tel %></dd>
           <dt>Address:</dt> <dd><%= @restaurant.address %></dd>
         </dl>
       </div>
     </div>
     <div class="col-md-8">
      <blockquote>
       <%= simple_format @restaurant.description %>
     </blockquote>
     </div>

     <div class="clearfix"></div>

     <hr>

   </div>
 </div>

  <nav aria-label>
    <ul class="pager">
      <li><%= link_to 'Back to index', admin_restaurants_path %></li>
    </ul>
  </nav>