config/routes.rb
Rails.application.routes.draw do
  # 實做新的 controller 去處理 callback
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
      get :feeds

      get :ranking
    end

    member do
      get :dashboard
      
      post :favorite
      post :unfavorite
      
      post :like
      post :unlike
    end
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :friend_list
    end
  end
  
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]  do
    member do
      post :confirm
      delete :reject
    end
  end

  resources :categories, only: :show
  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories 
    root "restaurants#index"
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates_presence_of :name

    mount_uploader :image, PhotoUploader
    belongs_to :category, optional: true

    has_many :comments, dependent: :destroy

    # 「餐廳被很多使用者收藏」的多對多關聯
    has_many :favorites, dependent: :destroy
    has_many :favorited_users, through: :favorites, source: :user

    def is_favorited?(user)
      self.favorited_users.include?(user)
    end
    
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    def is_liked?(user)
      self.liked_users.include?(user)   
    end


end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

def index
  @restaurants = Restaurant.page(params[:page]).per(9)
end

   def new
      @restaurant = Restaurant.new
   end

  def create
      @restaurant = Restaurant.new(restaurant_params)
      if @restaurant.save
        flash[:notice] = "Successfully created"
        redirect_to admin_restaurants_path
      else
        flash.now[:alert] = "Failed to create"
        render :new
      end
    end

    def show
    end

    def edit
    end

    def update
      if @restaurant.update(restaurant_params)
        redirect_to admin_restaurants_path(@restaurant)
        flash[:notice] = "Successfully updated"
      else
        render :edit
        flash[:alert] = "Failed to update"
      end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "Successfully deleted"
  end
 


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
    
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
     @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    @restaurant = Restaurant.find(params[:id])  
  end

  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    @restaurant.likes.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unlike
    @restaurant = Restaurant.find(params[:id])
    likes = Like.where(restaurant: @restaurant, user: current_user)
    likes.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def ranking
    @restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end
    
  end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/dashboard.html.erb
<div class="container">
   <div class="row">
     <div class="col-md-12">
      <h1><%= @restaurant.name %>'s Dashboard</h1>
      <hr>
      <blockquote>
        <ul>
          <li>有 <%= @restaurant.comments.count %> 筆評論</li>
          <li>這家餐廳的平均價位為 $XXX</li>
          <li>有 XX 人收藏這家餐廳</li>
        </ul>
      </blockquote>
    </div>
  </div>
</div>

app/views/restaurants/feeds.html.erb
<div class="container">
  <div class="row">
    <ul class="nav nav-tabs">
      <li role="presentation">
        <%= link_to "首頁", root_path %>
      </li>
      <li role="presentation"  class="active">
        <%= link_to "最新動態", feeds_restaurants_path %>
      </li>
      <li role="presentation">
        <%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %>
      </li>
      <li role="presentation">
        <%= link_to '美食達人', users_path %>
      </li>
    </ul>
  </div>
</div>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1 class="text-center">餐廳最新動態</h1>
      <hr>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">最新餐廳 <span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span></div>
          <div class="panel-body">
            <% @recent_restaurants.each do |restaurant| %>
              <div>
                <h4><%= link_to restaurant.name, restaurant_path(restaurant) %> <span class="label label-warning navbar-right"><%= restaurant.category.name %></span></h4>
                <p><%= truncate(restaurant.description, length:80) %></p>
                <hr>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">最新評論 <span class="glyphicon glyphicon-comment" aria-hidden="true"></span></div>
          <div class="panel-body">
            <% @recent_comments.each do |comment| %>
              <div>
                <h4><%= link_to comment.restaurant.name, restaurant_path(comment.restaurant) %> <span class="label label-warning navbar-right"><%= comment.restaurant.category.name %></span></h4>
                <p><%= comment.content %></p>
                <p>by <%= link_to comment.user.name, user_path(comment.user) %></p>
                <hr>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <ul class="nav nav-tabs">
      <li role="presentation" class="active">
        <%= link_to "首頁", root_path %>
      </li>
      <li role="presentation">
        <%= link_to "最新動態", feeds_restaurants_path %>
      </li>
      <li role="presentation">
        <%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %>
      </li>
      <li role="presentation">
        <%= link_to '美食達人', users_path %>
      </li>
    </ul>
  </div>
</div>
<br>

<div class="container">
  <div class="row">
  <ul class="nav nav-pills nav-pills-center">
    <li role="presentation" class="active"><%= link_to "全部餐廳", root_path %></li>
    <% @categories.each do |category| %>
      <li role="presentation"><%= link_to category.name, category_path(category) %></li>
    <% end %>
  </ul>
  <br>
      
    <%= render partial: "shared/restaurant_list" %>
      
  </div>
</div>

app/views/restaurants/ranking.html.erb
<div class="container">
  <div class="row">
    <ul class="nav nav-tabs">
      <li role="presentation">
        <%= link_to "首頁", root_path %>
      </li>
      <li role="presentation">
        <%= link_to "最新動態", feeds_restaurants_path %>
      </li>
      <li role="presentation"  class="active">
        <%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %>
      </li>
      <li role="presentation">
        <%= link_to '美食達人', users_path %>
      </li>
    </ul>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
    <h1 class="text-center">Top 10 人氣餐廳 <small>(收藏數最高)</small></h1>
    <hr>

    <% @restaurants.each do |restaurant| %>
      <div class="ranking-item">
        <%= link_to restaurant_path(restaurant) do %>
        <div class="col-md-3">
          <%= image_tag restaurant.image, class: "img-responsive center-block img-rounded" if restaurant.image?%>
          <%= image_tag "http://via.placeholder.com/240x160", class: "img-responsive center-block img-rounded"  unless restaurant.image?%> 
        </div>
        <% end %>
        <div class="col-md-9">
          <h4>
            <%= restaurant.name %>
            <span class="label label-warning navbar-right"><%= restaurant.category.name %></span>
          </h4>
          <p><%= truncate(restaurant.description, length: 200) %></p>
          <div>
            <span class="badge" style=" background-color: lightpink"><i class="glyphicon glyphicon-heart" aria-hidden="true"></i> <%= restaurant.favorites_count %></span>
            <%= render partial: 'shared/favorite', locals: { restaurant: restaurant } %>
            <%= link_to '<i class="glyphicon glyphicon-eye-open" aria-hidden="true"></i> 查看'.html_safe, restaurant_path(restaurant), class: "btn btn-default btn-sm" %>
          </div>
        </div>
        <div class="clearfix"></div>
      </div>
      <hr>
    <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
   <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
      <h4><span class="label label-warning"><%= @restaurant.category.name %></span></h4>
    </div>

    <div class="col-md-5">
       <%= image_tag @restaurant.image, class: "img-responsive center-block" if @restaurant.image?%>
      <%= image_tag "http://via.placeholder.com/460x305", class: "img-responsive center-block img-rounded"  unless @restaurant.image?%> 
       <br>
       <div class="well ">
         <dl class="row">
           <dt class="col-sm-4"><i class="glyphicon glyphicon-time" aria-hidden="true"></i> 營業時間：</dt><dd class="col-sm-8"><%= @restaurant.opening_hours %></dd>
           <dt class="col-sm-4"><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i> 店家電話：</dt><dd class="col-sm-8"><%= @restaurant.tel %></dd>
           <dt class="col-sm-4"><i class="glyphicon glyphicon-home" aria-hidden="true"></i> 店家地址：</dt><dd class="col-sm-8"><%= @restaurant.address %></dd>
         </dl>
       </div>
     </div>
     <div class="col-md-7">
      <blockquote>
       <%= simple_format @restaurant.description %>
     </blockquote>
      <hr>
      <span class="badge" style=" background-color: lightpink"><i class="glyphicon glyphicon-heart" aria-hidden="true"></i> <%= @restaurant.favorites_count %></span>
      <%= render partial: "shared/favorite", locals: {restaurant: @restaurant} %>
      <%= render partial: "shared/like", locals: {restaurant: @restaurant} %>

      <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#ModalCenter">
        <i class="glyphicon glyphicon-info-sign" aria-hidden="true"></i> Dashboard
      </button>

     </div>

      <%= render partial: "shared/dashboard", locals: {restaurant: @restaurant} %>

     <div class="clearfix"></div>

     <hr>

    <% @restaurant.comments.each do |comment| %>
      <div class="media">
        <div class="media-left">
          <%= image_tag "http://via.placeholder.com/64x64" %>
        </div>
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to user_path(comment.user) do %>
              <%= comment.user.name if comment.user.name? %>
              <%= comment.user.email.split("@").first unless comment.user.name? %>
            <% end %>
            <% if current_user.admin? %>
              <%= link_to '<i class="glyphicon glyphicon-trash" aria-hidden="true"></i> 刪除'.html_safe, restaurant_comment_path(@restaurant, comment), method: :delete ,class: "navbar-right btn btn-default btn-sm mark" %>
            <% end %>
          </h4>         
          <p><%= simple_format comment.content %></p>
          <p class="text-muted">
            <em>- <%= time_ago_in_words(comment.created_at) %> ago</em>
          </p>
        </div>
      </div>
     <hr>
    <% end %>


    <%= form_for [@restaurant, @comment] do |f| %>
      <div class="form-group">
        <%= f.text_area :content, placeholder: "留個言吧", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
        <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
      </div>
    <% end %>


   </div>
 </div>

  <nav aria-label>
    <ul class="pager">
      <li><%= link_to 'Back to index', restaurants_path %></li>
    </ul>
  </nav>