config/routes.rb
Rails.application.routes.draw do
  # 實做新的 controller 去處理 callback
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
      get :feeds

      get :ranking
    end

    member do
      get :dashboard
      
      post :favorite
      post :unfavorite
      
      post :like
      post :unlike
    end
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :friend_list
    end
  end
  
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]  do
    member do
      post :confirm
      delete :reject
    end
  end

  resources :categories, only: :show
  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories 
    root "restaurants#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant, counter_cache: true
end

app/models/followship.rb
class Followship < ApplicationRecord
  #uniqueness 方法在物件儲存前，驗證屬性值是否是唯一的，scope 可用另一個屬性來限制唯一性
  validates :following_id, uniqueness: { scope: :user_id }

  belongs_to :user
  belongs_to :following, class_name: "User"
end

app/models/friendship.rb
class Friendship < ApplicationRecord

  validates :friend_id, uniqueness: { scope: :user_id }

  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates_presence_of :name

    mount_uploader :image, PhotoUploader
    belongs_to :category, optional: true

    has_many :comments, dependent: :destroy

    # 「餐廳被很多使用者收藏」的多對多關聯
    has_many :favorites, dependent: :destroy
    has_many :favorited_users, through: :favorites, source: :user

    def is_favorited?(user)
      self.favorited_users.include?(user)
    end
    
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    def is_liked?(user)
      self.liked_users.include?(user)   
    end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.from_omniauth(auth)
    #Case 1: Find existing user by facebook uid
    # User不是第一次用FB登入：可以用fb_uid找到現存User
    user = User.find_by_fb_uid(auth.uid)
    if user
      user.fb_token = auth.credentials.token
      user.save!
      return user
    end

    #Case 2: Find existing user by email
    # User是第一次用FB登入，但是也是用同一組信箱帳號註冊過，就可以拿出FB回傳的email，從資料庫搜尋現存的User
    existing_user = User.find_by_email(auth.info.email)
    if existing_user
      existing_user.fb_uid = auth.uid
      existing_user.fb_token = auth.credentials.token
      existing_user.save!
      return existing_user
    end


    #Case 3: Create new password
    # User沒有註冊過，且是第一次用FB登入，故需創建一個全新的User紀錄
    user = Use.new
    user.fb_uid = auth.uid
    user.fb_token = auth.credentials.token
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.save!
    return user
  end

  validates_presence_of :name
  mount_uploader :avatar, AvatarUploader

  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  # 「使用者收藏很多餐廳」的多對多關聯
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  # 「使用者追蹤很多使用者」
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  # 「使用者的追蹤者」
  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  #「使用者新增很多朋友」
  has_many :friendships, -> {where status: true}, dependent: :destroy
  has_many :friends, through: :friendships

  #「使用者的朋友邀請」
  has_many :inverse_friendships, -> {where status: true}, class_name: "Friendship", foreign_key:"friend_id"
  has_many :inviters, through: :inverse_friendships, source: :user

  has_many :unconfirm_friendships, -> {where status: false}, class_name: "Friendship", dependent: :destroy
  has_many :unconfirm_friends, through: :unconfirm_friendships, source: :friend
  has_many :request_friendships, -> {where status: false}, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy
  has_many :request_friends, through: :request_friendships, source: :user

  def friend_receiver?(user)
    self.friends.include?(user) || self.inviters.include?(user)
  end

  def unconfirm_friend?(user)
    self.unconfirm_friends.include?(user)
  end

  def all_friends
    friends = self.friends + self.inviters
    return friends.uniq
  end

  def following?(user)
    self.followings.include?(user)
  end
  
  def admin?
    self.role == "admin"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :friend_list]

  def index
    @users = User.all
  end

  def show
    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings
    @followers = @user.followers
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def friend_list
    @friends = @user.all_friends 
    @unconfirm_friends = @user.unconfirm_friends
    @request_friends = @user.request_friends
  end


private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css">
  </head>

  <body>

      <nav class="navbar navbar-inverse">
       <div class="container-fluid">
         <!-- Brand and toggle get grouped for better mobile display -->
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <%= link_to '<i class="glyphicon glyphicon-home" aria-hidden="true"></i> 餐廳評論網 '.html_safe, root_path, class: "navbar-brand" %>
         </div>
 
         <!-- Collect the nav links, forms, and other content for toggling -->
         <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
           <ul class="pull-right text-right nav navbar-nav">
              <% if current_user %>
                <% if current_user.admin? %>
                  <li><%= link_to '<i class="glyphicon glyphicon-inbox" aria-hidden="true"></i> '.html_safe, admin_restaurants_path %></li>
                <% end %>
              <li><p class="navbar-text">Hi, <%= current_user.name %></p></li>
              <li><%= link_to '<i class="glyphicon glyphicon-user" aria-hidden="true"></i> '.html_safe, user_path(current_user) %></li>
              <li><%= link_to('<i class="glyphicon glyphicon-log-out" aria-hidden="true"></i> '.html_safe, destroy_user_session_path, method: :delete) %></li>
              <li><%= link_to('<i class="glyphicon glyphicon-wrench" aria-hidden="true"></i> '.html_safe, edit_user_registration_path) %></li>
              <% else %>
              <li><%= link_to('註冊', new_user_registration_path) %></li>
              <li><%= link_to('<i class="glyphicon glyphicon-log-in" aria-hidden="true"></i> '.html_safe, new_user_session_path) %></li>
             <% end %>
           </ul>
         </div>
       </div>
     </nav>

      <% if flash[:notice] %>
       <div class="container">
         <div class="row">
           <div class="alert alert-success alert-dismissible" role="alert">
             <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
             <%= notice %>
           </div>
         </div>
       </div>
       <% end %>
   
       <% if flash[:alert] %>
       <div class="container">
         <div class="row">
          <div class="alert alert-danger alert-dismissible" role="alert">
             <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
             <%= alert %>
          </div>
         </div>
       </div>
       <% end %>

    <%= yield %>

    <!-- Footer -->
    <footer id="footer" class="page-footer">
      <div class="container">
        <div class="footer-content">
          <p style="color: gray">&copy; 2017  Restaurant Forum | All Rights Reserved. </p>
          <div class="footer-social-icon">
            <ul>
                <a href=""><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a>
                <a href=""><i class="fa fa-github-alt" aria-hidden="true"></i></a>
                <a href=""><i class="fa fa-linkedin" aria-hidden="true"></i></a>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/shared/_dashboard.html.erb
<div class="modal fade" id="ModalCenter" tabindex="-1" role="dialog" aria-labelledby="ModalCenterTitle" aria-hidden="true" >
<div class="modal-dialog modal-dialog-centered" role="document" >
  <div class="modal-content" >
    <div class="modal-header" style= " background-color: #FFCC22 ">
      <h4 class="modal-title" id="ModalLongTitle"><i class="glyphicon glyphicon-info-sign" aria-hidden="true"></i> Dashboard</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
     <h1><%= restaurant.name %>'s Dashboard</h1>
      <hr>
      <blockquote>
        <ul class="list-unstyled">
          <li><i class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"></i> 有 <%= restaurant.comments.count %> 筆評論</li>
          <li><i class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"></i> 這家餐廳的平均價位為 $XXX</li>
          <li><i class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"></i> 有 XX 人收藏這家餐廳</li>
        </ul>
      </blockquote>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>
</div>

app/views/shared/_favorite.html.erb
<% if restaurant.is_favorited?(current_user) %>
  <%= link_to '<i class="glyphicon glyphicon-heart" aria-hidden="true"></i>'.html_safe, unfavorite_restaurant_path(restaurant), method: :post, class: "btn btn-link btn-lg", style:'color: crimson' %>
<% else %>
  <%= link_to '<i class="glyphicon glyphicon-heart" aria-hidden="true"></i>'.html_safe, favorite_restaurant_path(restaurant), method: :post, class: "btn btn-link btn-lg", style:'color: gray'  %>
<% end %>

app/views/shared/_follow.html.erb
<% if user != current_user %>
  <% if current_user.following?(user) %>
    <%= link_to ' 取消追蹤', followship_path(user), method: :delete, class: "btn btn-default btn-sm" %>
  <% else %>
    <%= link_to '<i class="glyphicon glyphicon-plus-sign" aria-hidden="true"></i> 追蹤'.html_safe, followships_path(following_id: user), method: :post, class: "btn btn-warning btn-sm" %>
  <% end %>
<% end %>

app/views/shared/_friend.html.erb
<% if user != current_user %>
  <% if current_user.friend_receiver?(user) %>
    <%= link_to '取消好友' , friendship_path(user), method: :delete, class: "btn btn-default btn-sm" %>
  <% elsif current_user.unconfirm_friend?(user) %>
    <%= link_to "取消邀請", friendship_path(user), class: "btn btn-danger btn-sm", method: :delete %>
  <% else %>
    <%= link_to '加入好友' , friendships_path(friend_id: user), method: :post, class: "btn btn-warning btn-sm" %>
  <% end %>
<% end %>

app/views/shared/_like.html.erb
 <% if restaurant.is_liked?(current_user) %>
  <%= link_to '<i class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></i>'.html_safe, unlike_restaurant_path(restaurant), method: :post, class: "btn btn-link btn-lg", style:'color: blue ' %>
<% else %>
  <%= link_to '<i class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></i>'.html_safe, like_restaurant_path(restaurant), method: :post, class: "btn btn-link btn-lg", style:'color: gray ' %>
<% end %>

app/views/shared/_restaurant_list.html.erb
     <% @restaurants.each do |restaurant| %>
      <div class="col-sm-6 col-md-4">
        <%= link_to restaurant_path(restaurant) do %>
          <div class="restaurant-item">
            <div>
            <%= image_tag restaurant.image, class: "img-responsive center-block img-rounded" if restaurant.image?%>
            <%= image_tag "http://via.placeholder.com/338x180", class: "img-responsive center-block img-rounded"  unless restaurant.image?%> 
            </div>
            <div class="caption">
              <h3 class="title"><%= restaurant.name %>
                <small class="navbar-right tag"><span class="label label-warning"><%= restaurant.category.name %></span></small></h3>
              <p style="color:black"><%= truncate(restaurant.description, length: 80) %></p>
              <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
              <%= render partial: "shared/like", locals: {restaurant: restaurant} %>
              <button type="button" class="btn btn-link btn-lg" data-toggle="modal" data-target="#ModalCenter">
                <i class="glyphicon glyphicon-info-sign" aria-hidden="true"></i>
              </button>
            </div>
          </div>
          <%= render partial: "shared/dashboard", locals: {restaurant: restaurant} %>
        <% end %>
      </div>
    <% end %>
      
    <div class="text-center">
      <%= paginate @restaurants %>
    </div>
      